const app=document.querySelector('#app');
const courses=[
 {id:'chest-back',name:'胸背两分化',intro:'推拉交替，动作可按器械替换。',steps:[
  {actionId:'bench',name:'杠铃卧推',sets:'默认 2 工作组 × 8–12 次 · 休息 150 秒',cue:'水平推：肩胛稳定，杠铃落点可控。',alternatives:['pushup','machine-press']},
  {actionId:'row',name:'坐姿划船',sets:'默认 2 工作组 × 8–12 次 · 休息 120 秒',cue:'水平拉：肘向后带，躯干保持稳定。',alternatives:['chest-row']},
  {actionId:'incline',name:'哑铃上斜卧推',sets:'默认 2 工作组 × 8–12 次 · 休息 120 秒',cue:'上斜推：上斜角度适中，手腕中立。',alternatives:['machine-press','pushup']},
  {actionId:'pulldown',name:'高位下拉',sets:'默认 2 工作组 × 8–12 次 · 休息 120 秒',cue:'垂直拉：先下沉肩胛，再向下拉肘。',alternatives:['assist-pullup']}
 ]},
 {id:'glute-leg',name:'臀腿两分化',intro:'髋主导与膝主导兼顾，按当天器械选择。',steps:[
  {actionId:'squat',name:'深蹲',sets:'默认 2 工作组 × 8–12 次 · 休息 150 秒',cue:'膝主导：脚掌稳定，膝盖跟随脚尖。',alternatives:['leg-press','goblet-squat']},
  {actionId:'r',name:'罗马尼亚硬拉',sets:'默认 2 工作组 × 8–12 次 · 休息 150 秒',cue:'髋铰链：髋向后移，背部中立。',alternatives:['hip-hinge']},
  {actionId:'standing-cable-hip-extension',name:'站姿绳索后踢腿',sets:'默认 2 工作组 × 10–15 次 · 休息 90 秒',cue:'髋伸槽位：使用已读完整教学来源。',alternatives:[]},
  {actionId:'prone-leg-curl',name:'俯身腿弯曲',sets:'默认 2 工作组 × 10–15 次 · 休息 90 秒',cue:'屈膝槽位：使用已读完整教学来源。',alternatives:[]}
 ]}
];
const atoms={bench:{name:'杠铃卧推',source:'已读参考：杠铃卧推',ref:'barbell-bench-press',detail:'加载现有参考动作详情。'},incline:{name:'哑铃上斜卧推',source:'已读参考：上斜哑铃卧推',ref:'incline-dumbbell-chest-press',detail:'加载现有参考动作详情。'},r:{name:'罗马尼亚硬拉',source:'已读参考：罗马尼亚硬拉',ref:'romanian-deadlift',detail:'加载现有参考动作详情。'},row:{name:'窄距坐姿划船',source:'已读参考：窄距坐姿划船',ref:'narrow-seated-row',detail:'加载现有参考动作详情。'},pulldown:{name:'高位下拉',source:'已读参考：高位下拉',ref:'angled-handle-lat-pulldown',detail:'加载现有参考动作详情。'},pushup:{name:'俯卧撑',source:'未配置可靠教学来源',detail:'不作为现有课程技术复用。'},'machine-press':{name:'器械推胸',source:'未配置可靠教学来源',detail:'不作为现有课程技术复用。'},squat:{name:'深蹲模式',source:'已读参考：深蹲模式',ref:'squat-pattern',detail:'加载现有参考动作详情。'},'standing-cable-hip-extension':{name:'站姿绳索后踢腿',source:'已读参考：站姿绳索后踢腿',ref:'standing-cable-hip-extension',detail:'加载现有参考动作详情。'},'prone-leg-curl':{name:'俯身腿弯曲',source:'已读参考：俯身腿弯曲',ref:'prone-leg-curl',detail:'加载现有参考动作详情。'}};
let referenceEntries=[];fetch('./data/authorized-reference.json').then(r=>r.json()).then(x=>{referenceEntries=x.entries||[];if(location.hash.startsWith('#course/'))route()});
Object.assign(atoms,{'chest-row':{name:'胸托划船',source:'未配置已读来源',detail:'保持水平拉槽位；在补充可靠动作资料前不作为原课技术复用。'},'assist-pullup':{name:'辅助引体',source:'未配置已读来源',detail:'保持垂直拉槽位；在补充可靠动作资料前不作为原课技术复用。'},'hip-hinge':{name:'髋铰链练习',source:'参考：Romanian Deadlift（已读）',detail:'保持髋铰链模式，不把背伸或拉臀冒充为等价替换。'},'leg-press':{name:'腿举',source:'未配置已读来源',detail:'保持膝主导槽位。'},'goblet-squat':{name:'高脚杯深蹲',source:'现有课程：高脚杯深蹲',detail:'保持膝主导槽位。'},'glute-bridge':{name:'臀桥',source:'未配置可靠教学来源',detail:'未配置时不作为已教动作。'},'cable-pullthrough':{name:'绳索拉臀',source:'未配置可靠教学来源',detail:'未配置时不作为已教动作。'}});
const getCourse=id=>courses.find(x=>x.id===id),atom=id=>atoms[id]||{name:id,source:'可替换动作',detail:'按现有器械和状态选择。'};
const replacementKey='training-course-replacements-v1';let replacements={};try{replacements=JSON.parse(localStorage.getItem(replacementKey)||'{}')}catch{}const chosen=(c,i)=>replacements[c.id+'/'+i]||c.steps[i].actionId;const saveChoice=(c,i,id)=>{replacements[c.id+'/'+i]=id;localStorage.setItem(replacementKey,JSON.stringify(replacements))};
const executionKey='training-course-execution-v1';let execution={};try{execution=JSON.parse(localStorage.getItem(executionKey)||'{}')}catch{}const slotKey=(c,i)=>c.id+'/'+i;const slot=(c,i)=>execution[slotKey(c,i)]||{done:0,rest:null};const saveExecution=()=>localStorage.setItem(executionKey,JSON.stringify(execution));const remain=r=>r.paused?r.remaining:Math.max(0,r.deadline-Date.now());const clock=ms=>{let s=Math.ceil(Math.max(0,ms)/1000);return String(Math.floor(s/60)).padStart(2,'0')+':'+String(s%60).padStart(2,'0')};
const href=(c,i,detail)=>'#course/'+c.id+'/'+i+(detail?'/exercise/'+detail:'');
function list(){app.innerHTML='<section data-testid=course-root class=hero><h1>训练课</h1><p class=sub>两分化课程 · 稳定动作 ID · 可替换卡片</p></section><div class=filters><button data-testid=course-library>内容资料</button><button data-testid=course-training>训练工具</button></div>'+courses.map(c=>'<article class=card><h2>'+c.name+'</h2><p>'+c.intro+'</p><p class=muted>'+c.steps.length+' 个动作步骤</p><a class="back primary" data-testid=course-open href="#course/'+c.id+'/0">开始课程</a></article>').join('')}
function detail(c,index,id){let a=atom(id),r=referenceEntries.find(x=>x.id===a.ref),ps=r?(r.main?.paragraphs||r.trainingDetails?.paragraphs||[]):[],steps=r?(r.stepSequences||[]).flatMap(x=>x.steps||[]):[],links=r?(r.primarySources||[]):[],pic=r?.media?.src||r?.publicImages?.[0]?.url||r?.publicImages?.[0],image=pic?'<img src="'+pic+'" alt="'+a.name+' 动作示意">':'',label=(x,i)=>r?.id==='prone-leg-curl'&&i===2?'受控回程':r?.id==='standing-cable-hip-extension'?'步骤 '+(i+1):(x.title||'步骤');app.innerHTML='<button class=back data-testid=course-detail-back>← 返回步骤</button><article data-testid=course-atom-detail class="card detail"><h1>'+a.name+'</h1><p class=muted>'+a.source+' · 组次为新增编排建议</p>'+image+(ps.length?'<section><h3>原始技术说明</h3>'+ps.map(x=>'<p>'+x+'</p>').join('')+'</section>':'<p>'+a.detail+'</p>')+(steps.length?'<section><h3>执行步骤</h3>'+steps.map((x,i)=>'<p><b>'+(i+1)+'. '+label(x,i)+'</b><br>'+x.text+'</p>').join('')+'</section>':'')+(r?.sourceRecord?.paragraphs?.length?'<details><summary>原始来源记录</summary>'+r.sourceRecord.paragraphs.map(x=>'<p>'+x+'</p>').join('')+'</details>':'')+(links.length?'<p>'+links.map(x=>'<a class="back primary" href="'+x.url+'">'+(x.label||x.timeText||'查看原始来源')+'</a>').join(' ')+'</p>':'')+'</article>'}
function route(){let m=location.hash.match(/^#course\/([^/]+)\/(\d+)(?:\/exercise\/([^/]+))?$/);if(location.hash==='#courses')return list();if(!m)return;let c=getCourse(m[1]),i=Number(m[2]);if(!c||!c.steps[i]){location.hash='#courses';return}m[3]?detail(c,i,m[3]):steps(c,i)}
document.addEventListener('click',e=>{let b=e.target.closest('[data-testid]');if(!b||!app.contains(b))return;if(b.dataset.testid==='course-library'){e.preventDefault();e.stopImmediatePropagation();location.hash='content'}if(b.dataset.testid==='course-training'){e.preventDefault();e.stopImmediatePropagation();location.hash='training';location.reload()}if(b.dataset.testid==='course-atom'||b.dataset.testid==='course-replace'){let m=location.hash.match(/^#course\/([^/]+)\/(\d+)/);if(m){e.preventDefault();e.stopImmediatePropagation();let c=getCourse(m[1]),i=Number(m[2]);if(b.dataset.testid==='course-replace'){let old=slot(c,i);if(old.done&&!confirm('替换动作会重置该槽已完成组数与休息，继续吗？'))return;saveChoice(c,i,b.dataset.atom);delete execution[slotKey(c,i)];saveExecution()}location.hash=href(c,i,b.dataset.atom)}}if(b.dataset.testid==='course-detail-back'){let m=location.hash.match(/^#course\/([^/]+)\/(\d+)/);if(m){e.preventDefault();e.stopImmediatePropagation();location.hash='#course/'+m[1]+'/'+m[2]}}},true);
window.addEventListener('hashchange',route);window.addEventListener('popstate',route);
const observer=new MutationObserver(()=>{if(location.hash===''||location.hash==='#content'){let root=app.querySelector('[data-testid=content-root]');if(root&&!app.querySelector('[data-testid=course-tab]')){let b=document.createElement('button');b.dataset.testid='course-tab';b.textContent='训练课';root.after(b)}}});observer.observe(app,{childList:true,subtree:true});
document.addEventListener('click',e=>{let b=e.target.closest('[data-testid=course-tab]');if(b){e.stopImmediatePropagation();location.hash='courses'}},true);
function steps(c,index){
 const s=c.steps[index],action=chosen(c,index);
 app.innerHTML='<section data-testid=course-steps class=hero><p class=muted>'+c.name+' · '+(index+1)+'/'+c.steps.length+'</p><h1>'+atom(action).name+'</h1><p>'+s.sets+' · 留 2–3 次余力 · 休息 90–180 秒（可调）</p><p>'+atom(action).detail+'</p><p class=muted>热身 5–10 分钟；首个大项可做 1–2 轻热身组（不计工作组）。这是保守模板，不是原视频处方；时长 30–45 分钟仅为估计。</p></section><article class=card><h2>动作卡</h2><button data-testid=course-atom data-atom="'+action+'">'+atom(action).name+' · 查看要点</button><h3>同模式替换</h3><div class=filters>'+s.alternatives.map(id=>'<button data-testid=course-replace data-atom="'+id+'">'+atom(id).name+'</button>').join('')+'</div></article><div id=course-execution></div><div class=actions><a class=back href="#courses">返回课程</a>'+(index?'<a class=back href="'+href(c,index-1)+'">上一项</a>':'')+(index<c.steps.length-1?'<a class="back primary" href="'+href(c,index+1)+'">下一项</a>':'')+'</div>';renderExecution(c,index);
}
function renderExecution(c,i){let box=document.querySelector('#course-execution');if(!box)return;let x=slot(c,i),r=x.rest;box.innerHTML='<article data-testid=course-execution class=card><h2>执行</h2><p data-testid=course-progress>已完成 '+x.done+' / 2 组</p><label>休息 <select data-testid=rest-seconds>'+[90,120,150,180].map(n=>'<option '+((r?.duration||120)===n?'selected':'')+'>'+n+'</option>').join('')+'</select> 秒</label><p class=timer data-testid=course-rest-timer>'+ (r?clock(remain(r)):'准备开始')+'</p><div class=actions><button data-testid=course-set-done>完成一组</button><button data-testid=course-set-undo>撤销一组</button>'+(r?'<button data-testid=course-rest-pause>'+ (r.paused?'继续':'暂停')+'</button><button data-testid=course-rest-skip>跳过休息</button>':'')+'</div></article>'}
setInterval(()=>{let m=location.hash.match(/^#course\/([^/]+)\/(\d+)/);if(!m)return;let c=getCourse(m[1]),i=Number(m[2]),x=c&&slot(c,i);if(x?.rest&&!x.rest.paused){if(remain(x.rest)<=0){x.rest=null;saveExecution();renderExecution(c,i)}else{let t=document.querySelector('[data-testid=course-rest-timer]');if(t)t.textContent=clock(remain(x.rest))}}},250);
document.addEventListener('click',e=>{let b=e.target.closest('[data-testid^=course-set],[data-testid^=course-rest]');if(!b||!app.contains(b))return;let m=location.hash.match(/^#course\/([^/]+)\/(\d+)/);if(!m)return;let c=getCourse(m[1]),i=Number(m[2]),x=slot(c,i);e.stopImmediatePropagation();if(b.dataset.testid==='course-set-done'&&x.done<2){x.done++;let duration=Number(document.querySelector('[data-testid=rest-seconds]').value);x.rest={duration,deadline:Date.now()+duration*1000,paused:false};execution[slotKey(c,i)]=x}if(b.dataset.testid==='course-set-undo'&&x.done){x.done--;x.rest=null;execution[slotKey(c,i)]=x}if(b.dataset.testid==='course-rest-pause'){if(x.rest.paused){x.rest.deadline=Date.now()+x.rest.remaining;x.rest.paused=false}else{x.rest.remaining=remain(x.rest);x.rest.paused=true}}if(b.dataset.testid==='course-rest-skip'){x.rest=null}saveExecution();renderExecution(c,i)},true);
route();
