const {chromium}=require('playwright');
(async()=>{
 const b=await chromium.launch({headless:true,executablePath:'/usr/bin/chromium',args:['--no-sandbox']});
 const p=await b.newPage({viewport:{width:390,height:844}}),errors=[];p.setDefaultTimeout(5000);p.on('pageerror',e=>errors.push(e.message));
 await p.route('**/*',r=>r.request().url().startsWith('http://127.0.0.1:4173/')?r.continue():r.abort());
 await p.goto('http://127.0.0.1:4173#courses');await p.getByTestId('course-root').waitFor();
 if(await p.locator('a[href^="#course/"]').count()!==2)throw Error('two split templates');
 await p.locator('a[href="#course/chest-back/0"]').click();await p.getByTestId('course-steps').waitFor();
 await p.getByTestId('course-rest').selectOption('90');await p.getByTestId('course-set').click();await p.getByTestId('course-rest-timer').waitFor();
 await p.getByTestId('course-pause').click();let paused=await p.getByTestId('course-rest-timer').textContent();await p.reload();await p.getByTestId('course-rest-timer').waitFor();
 if(await p.getByTestId('course-rest-timer').textContent()!==paused)throw Error('paused rest refresh');
 if(await p.getByTestId('course-rest').inputValue()!=='90')throw Error('rest choice persisted');
 await p.getByTestId('course-undo').click();if(!(await p.getByTestId('course-progress').textContent()).includes('0 / 2'))throw Error('set undo');
 await p.goto('http://127.0.0.1:4173#course/glute-leg/0');await p.getByTestId('course-steps').waitFor();
 p.once('dialog',d=>d.dismiss());await p.getByTestId('course-replace').nth(1).click();if((await p.getByTestId('course-atom').getAttribute('data-atom'))!=='squat-pattern')throw Error('replacement cancel');
 p.once('dialog',d=>d.accept());await p.getByTestId('course-replace').nth(1).click();await p.getByTestId('course-steps').waitFor();await p.getByTestId('course-atom').click();await p.getByTestId('course-atom-detail').waitFor();
 await p.getByTestId('course-detail-back').click();await p.getByTestId('course-steps').waitFor();
 await p.goto('http://127.0.0.1:4173#course/glute-leg/0/exercise/BV17aovBqEdg%3Agoblet_squat');await p.getByTestId('course-atom-detail').waitFor();await p.goBack();await p.getByTestId('course-steps').waitFor();await p.goForward();await p.getByTestId('course-atom-detail').waitFor();
 await p.goto('http://127.0.0.1:4173#courses');await p.getByTestId('course-training').click();await p.waitForFunction(()=>location.hash==='#training');await p.getByRole('button',{name:'训练计划'}).waitFor();
 if(errors.length)throw Error(errors.join('\n'));await b.close();console.log('training course passed');
})().catch(e=>{console.error(e);process.exit(1)});
